// ALL COMMENTS  CONSTANTS 
export const ALL_COMMENTS_REQUEST = 'ALL_COMMENTS_REQUEST'
export const ALL_COMMENTS_SUCCESS = 'ALL_COMMENTS_SUCCESS'
export const ALL_COMMENTS_FAIL = 'ALL_COMMENTS_FAIL'
export const ALL_COMMENTS_RESET = 'ALL_COMMENTS_RESET'

// // USER TIMELINE COMMENTS  CONSTANTS 
export const USER_TIMELINE_COMMENTS_REQUEST = 'USER_TIMELINE_COMMENTS_REQUEST'
export const USER_TIMELINE_COMMENTS_SUCCESS = 'USER_TIMELINE_COMMENTS_SUCCESS'
export const USER_TIMELINE_COMMENTS_FAIL = 'USER_TIMELINE_COMMENTS_FAIL'
export const USER_TIMELINE_COMMENTS_RESET = 'USER_TIMELINE_COMMENTS_RESET'

// CREATE COMMENTS CONSTANTS 
export const CREATE_COMMENTS_REQUEST = 'CREATE_COMMENTS_REQUEST'
export const CREATE_COMMENTS_SUCCESS = 'CREATE_COMMENTS_SUCCESS'
export const CREATE_COMMENTS_FAIL = 'CREATE_COMMENTS_FAIL'
export const CREATE_COMMENTS_RESET = 'CREATE_COMMENTS_RESET'

// USER COMMENTS CONSTANTS
export const USER_COMMENTS_REQUEST = 'USER_COMMENTS_REQUEST'
export const USER_COMMENTS_SUCCESS = 'USER_COMMENTS_SUCCESS'
export const USER_COMMENTS_FAIL = 'USER_COMMENTS_FAIL'
export const USER_COMMENTS_RESET = 'USER_COMMENTS_RESET'

// UPDATE COMMENTS CONSTANTS 
export const UPDATE_COMMENTS_REQUEST = 'UPDATE_COMMENTS_REQUEST'
export const UPDATE_COMMENTS_SUCCESS = 'UPDATE_COMMENTS_SUCCESS'
export const UPDATE_COMMENTS_FAIL = 'UPDATE_COMMENTS_FAIL'
export const UPDATE_COMMENTS_RESET = 'UPDATE_COMMENTS_RESET'

// DELETE COMMENTS CONSTANTS 
export const DELETE_COMMENTS_REQUEST = 'DELETE_COMMENTS_REQUEST'
export const DELETE_COMMENTS_SUCCESS = 'DELETE_COMMENTS_SUCCESS'
export const DELETE_COMMENTS_FAIL = 'DELETE_COMMENTS_FAIL'
export const DELETE_COMMENTS_RESET = 'DELETE_COMMENTS_RESET'

// LIKE COMMENTS CONSTANTS 
export const LIKE_COMMENTS_REQUEST = 'LIKE_COMMENTS_REQUEST'
export const LIKE_COMMENTS_SUCCESS = 'LIKE_COMMENTS_SUCCESS'
export const LIKE_COMMENTS_FAIL = 'LIKE_COMMENTS_FAIL'
export const LIKE_COMMENTS_RESET = 'LIKE_COMMENTS_RESET'

// DISLIKE COMMENTS CONSTANTS 
export const DISLIKE_COMMENTS_REQUEST = 'DISLIKE_COMMENTS_REQUEST'
export const DISLIKE_COMMENTS_SUCCESS = 'DISLIKE_COMMENTS_SUCCESS'
export const DISLIKE_COMMENTS_FAIL = 'DISLIKE_COMMENTS_FAIL'
export const DISLIKE_COMMENTS_RESET = 'DISLIKE_COMMENTS_RESET'
