// ALL POSTS  CONSTANTS 
export const ALL_POSTS_REQUEST = 'ALL_POSTS_REQUEST'
export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS'
export const ALL_POSTS_FAIL = 'ALL_POSTS_FAIL'
export const ALL_POSTS_RESET = 'ALL_POSTS_RESET'

// // USER TIMELINE POSTS  CONSTANTS 
export const USER_TIMELINE_POSTS_REQUEST = 'USER_TIMELINE_POSTS_REQUEST'
export const USER_TIMELINE_POSTS_SUCCESS = 'USER_TIMELINE_POSTS_SUCCESS'
export const USER_TIMELINE_POSTS_FAIL = 'USER_TIMELINE_POSTS_FAIL'
export const USER_TIMELINE_POSTS_RESET = 'USER_TIMELINE_POSTS_RESET'

// CREATE POST CONSTANTS 
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'
export const CREATE_POST_RESET = 'CREATE_POST_RESET'

// USER POSTS CONSTANTS
export const USER_POSTS_REQUEST = 'USER_POSTS_REQUEST'
export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS'
export const USER_POSTS_FAIL = 'USER_POSTS_FAIL'
export const USER_POSTS_RESET = 'USER_POSTS_RESET'

// UPDATE POST CONSTANTS 
export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'
export const UPDATE_POST_RESET = 'UPDATE_POST_RESET'

// DELETE POST CONSTANTS 
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
export const DELETE_POST_RESET = 'DELETE_POST_RESET'

// LIKE POST CONSTANTS 
export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL'
export const LIKE_POST_RESET = 'LIKE_POST_RESET'

// DISLIKE POST CONSTANTS 
export const DISLIKE_POST_REQUEST = 'DISLIKE_POST_REQUEST'
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS'
export const DISLIKE_POST_FAIL = 'DISLIKE_POST_FAIL'
export const DISLIKE_POST_RESET = 'DISLIKE_POST_RESET'
