// LOAD USER CONSTANTS 
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'
export const LOAD_USER_RESET = 'LOAD_USER_RESET'

// GET USER CONSTANTS 
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'
export const GET_USER_RESET = 'GET_USER_RESET'

// GET USER CONSTANTS 
export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL'
export const FOLLOW_USER_RESET = 'FOLLOW_USER_RESET'

// GET USER CONSTANTS 
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const GET_USERS_RESET = 'GET_USERS_RESET'

// UNFOLLOW USER CONSTANTS 
export const UNFOLLOW_USERS_REQUEST = 'UNFOLLOW_USERS_REQUEST'
export const UNFOLLOW_USERS_SUCCESS = 'UNFOLLOW_USERS_SUCCESS'
export const UNFOLLOW_USERS_FAIL = 'UNFOLLOW_USERS_FAIL'
export const UNFOLLOW_USERS_RESET = 'UNFOLLOW_USERS_RESET'

// GET USER POSTS CONSTANTS 
export const GET_USER_POST_REQUEST = 'GET_USER_POST_REQUEST'
export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS'
export const GET_USER_POST_FAIL = 'GET_USER_POST_FAIL'
export const GET_USER_POST_RESET = 'GET_USER_POST_RESET'

// CLEAR ERRORS
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
