// LOAD USER CONSTANTS 
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'
export const LOAD_USER_RESET = 'LOAD_USER_RESET'

// GET USER CONSTANTS 
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'
export const GET_USER_RESET = 'GET_USER_RESET'

// GET USER POSTS CONSTANTS 
export const GET_USER_POST_REQUEST = 'GET_USER_POST_REQUEST'
export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS'
export const GET_USER_POST_FAIL = 'GET_USER_POST_FAIL'
export const GET_USER_POST_RESET = 'GET_USER_POST_RESET'

// CLEAR ERRORS
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
